// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./src/components/Star.vue')['default']
  }
}

export {}
