/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogList: typeof import('./components/BlogList.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Plum: typeof import('./components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./components/WrapperPost.vue')['default']
  }
}
